In [1]:
import numpy as np

In [2]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [3]:
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [4]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [5]:
arr.max()

95

In [7]:
arr.argmax()

0

In [8]:
arr.argmin()

7

In [9]:
arr.mean()

60.8

In [10]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])